# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultlocale.1.0.0.schema.json
PackageIdentifier: RomainBourdon.Wampserver
PackageVersion: 3.2.3
PackageLocale: en-US
Publisher: Romain Bourdon
Author: Romain Bourdon
PackageName: Wampserver
PackageUrl: https://www.wampserver.com
License: GPML
ShortDescription: WampServer is a Windows web development environment. It allows you to create web applications with Apache2, PHP and a MySQL database.
Moniker: wamp
Tags:
  - Webserver
  - PHP
  - MySQL
  - Apache2
ManifestType: defaultLocale
ManifestVersion: 1.0.0
